// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `MoveBaseActionPrxHelper.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package eu.nifti.Planning.slice;

public final class MoveBaseActionPrxHelper extends Ice.ObjectPrxHelperBase implements MoveBaseActionPrx
{
    public static MoveBaseActionPrx
    checkedCast(Ice.ObjectPrx __obj)
    {
        MoveBaseActionPrx __d = null;
        if(__obj != null)
        {
            try
            {
                __d = (MoveBaseActionPrx)__obj;
            }
            catch(ClassCastException ex)
            {
                if(__obj.ice_isA(ice_staticId()))
                {
                    MoveBaseActionPrxHelper __h = new MoveBaseActionPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static MoveBaseActionPrx
    checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        MoveBaseActionPrx __d = null;
        if(__obj != null)
        {
            try
            {
                __d = (MoveBaseActionPrx)__obj;
            }
            catch(ClassCastException ex)
            {
                if(__obj.ice_isA(ice_staticId(), __ctx))
                {
                    MoveBaseActionPrxHelper __h = new MoveBaseActionPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static MoveBaseActionPrx
    checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        MoveBaseActionPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId()))
                {
                    MoveBaseActionPrxHelper __h = new MoveBaseActionPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static MoveBaseActionPrx
    checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        MoveBaseActionPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId(), __ctx))
                {
                    MoveBaseActionPrxHelper __h = new MoveBaseActionPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static MoveBaseActionPrx
    uncheckedCast(Ice.ObjectPrx __obj)
    {
        MoveBaseActionPrx __d = null;
        if(__obj != null)
        {
            try
            {
                __d = (MoveBaseActionPrx)__obj;
            }
            catch(ClassCastException ex)
            {
                MoveBaseActionPrxHelper __h = new MoveBaseActionPrxHelper();
                __h.__copyFrom(__obj);
                __d = __h;
            }
        }
        return __d;
    }

    public static MoveBaseActionPrx
    uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        MoveBaseActionPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            MoveBaseActionPrxHelper __h = new MoveBaseActionPrxHelper();
            __h.__copyFrom(__bb);
            __d = __h;
        }
        return __d;
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::eu::nifti::Planning::slice::Action",
        "::eu::nifti::Planning::slice::MoveBaseAction"
    };

    public static String
    ice_staticId()
    {
        return __ids[2];
    }

    protected Ice._ObjectDelM
    __createDelegateM()
    {
        return new _MoveBaseActionDelM();
    }

    protected Ice._ObjectDelD
    __createDelegateD()
    {
        return new _MoveBaseActionDelD();
    }

    public static void
    __write(IceInternal.BasicStream __os, MoveBaseActionPrx v)
    {
        __os.writeProxy(v);
    }

    public static MoveBaseActionPrx
    __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            MoveBaseActionPrxHelper result = new MoveBaseActionPrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }
}
