// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `ControllersStatus.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package eu.nifti.env.status;

public class ControllersStatus extends Ice.ObjectImpl
{
    public ControllersStatus()
    {
    }

    public ControllersStatus(int core, int trackLeft, int trackRight, int flipperFrontLeft, int flipperFrontRight, int flipperRearLeft, int flipperRearRight)
    {
        this.core = core;
        this.trackLeft = trackLeft;
        this.trackRight = trackRight;
        this.flipperFrontLeft = flipperFrontLeft;
        this.flipperFrontRight = flipperFrontRight;
        this.flipperRearLeft = flipperRearLeft;
        this.flipperRearRight = flipperRearRight;
    }

    private static class __F implements Ice.ObjectFactory
    {
        public Ice.Object
        create(String type)
        {
            assert(type.equals(ice_staticId()));
            return new ControllersStatus();
        }

        public void
        destroy()
        {
        }
    }
    private static Ice.ObjectFactory _factory = new __F();

    public static Ice.ObjectFactory
    ice_factory()
    {
        return _factory;
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::eu::nifti::env::status::ControllersStatus"
    };

    public boolean
    ice_isA(String s)
    {
        return java.util.Arrays.binarySearch(__ids, s) >= 0;
    }

    public boolean
    ice_isA(String s, Ice.Current __current)
    {
        return java.util.Arrays.binarySearch(__ids, s) >= 0;
    }

    public String[]
    ice_ids()
    {
        return __ids;
    }

    public String[]
    ice_ids(Ice.Current __current)
    {
        return __ids;
    }

    public String
    ice_id()
    {
        return __ids[1];
    }

    public String
    ice_id(Ice.Current __current)
    {
        return __ids[1];
    }

    public static String
    ice_staticId()
    {
        return __ids[1];
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeTypeId(ice_staticId());
        __os.startWriteSlice();
        __os.writeInt(core);
        __os.writeInt(trackLeft);
        __os.writeInt(trackRight);
        __os.writeInt(flipperFrontLeft);
        __os.writeInt(flipperFrontRight);
        __os.writeInt(flipperRearLeft);
        __os.writeInt(flipperRearRight);
        __os.endWriteSlice();
        super.__write(__os);
    }

    public void
    __read(IceInternal.BasicStream __is, boolean __rid)
    {
        if(__rid)
        {
            __is.readTypeId();
        }
        __is.startReadSlice();
        core = __is.readInt();
        trackLeft = __is.readInt();
        trackRight = __is.readInt();
        flipperFrontLeft = __is.readInt();
        flipperFrontRight = __is.readInt();
        flipperRearLeft = __is.readInt();
        flipperRearRight = __is.readInt();
        __is.endReadSlice();
        super.__read(__is, true);
    }

    public void
    __write(Ice.OutputStream __outS)
    {
        Ice.MarshalException ex = new Ice.MarshalException();
        ex.reason = "type eu::nifti::env::status::ControllersStatus was not generated with stream support";
        throw ex;
    }

    public void
    __read(Ice.InputStream __inS, boolean __rid)
    {
        Ice.MarshalException ex = new Ice.MarshalException();
        ex.reason = "type eu::nifti::env::status::ControllersStatus was not generated with stream support";
        throw ex;
    }

    public int core;

    public int trackLeft;

    public int trackRight;

    public int flipperFrontLeft;

    public int flipperFrontRight;

    public int flipperRearLeft;

    public int flipperRearRight;
}
